################################################################################
# distributor_apis.yaml
#
# Check and verify library integrity with distributor APIs.
################################################################################

name: Distributor Check

on: [ push, pull_request ]

jobs:
  run_pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/distributor_apis/requirements.txt
          pip install pytest pytest-cov

      - name: Run pytest
        env:
          DIGIKEY_API_CLIENT_ID: ${{ secrets.DIGIKEY_API_CLIENT_ID }}
          DIGIKEY_API_CLIENT_SECRET: ${{ secrets.DIGIKEY_API_CLIENT_SECRET }}
          MOUSER_API_KEY: ${{ secrets.MOUSER_API_KEY }}
          MOUSER_API_VERSION: ${{ secrets.MOUSER_API_VERSION }}
          # NOTE: Setup as GitHub organization or repository secrets.
        run: coverage run -m pytest .github/workflows/distributor_apis -v -s

      - name: Generate Coverage Report
        run: |
          coverage report -m

  check_library_integrity:
    needs: run_pytest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/distributor_apis/requirements.txt

      - name: Run script
        env:
          DIGIKEY_API_CLIENT_ID: ${{ secrets.DIGIKEY_API_CLIENT_ID }}
          DIGIKEY_API_CLIENT_SECRET: ${{ secrets.DIGIKEY_API_CLIENT_SECRET }}
          MOUSER_API_KEY: ${{ secrets.MOUSER_API_KEY }}
          MOUSER_API_VERSION: ${{ secrets.MOUSER_API_VERSION }}
          # NOTE: Setup as GitHub organization or repository secrets.
        run: python .github/workflows/distributor_apis/main.py
